import type { Poi } from "./types";

export const INITIAL_POIS: Poi[] = [
  {
    id: "s-1",
    type: "scooter",
    lat: 52.52,
    lng: 13.405,
    name: "line e-scooter #104",
    provider: "line",
    battery: 88,
    model: "L1",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 1, perMinute: 0.24, perKm: 0.15 },
  },
  {
    id: "s-2",
    type: "scooter",
    lat: 52.518,
    lng: 13.399,
    name: "line e-scooter #327",
    provider: "line",
    battery: 64,
    model: "L2",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 1, perMinute: 0.22, perKm: 0.14 },
  },
  {
    id: "s-3",
    type: "scooter",
    lat: 52.516,
    lng: 13.413,
    name: "bult e-scooter #205",
    provider: "bult",
    battery: 51,
    model: "B-Spark",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 1.2, perMinute: 0.25, perKm: 0.16 },
  },
  {
    id: "s-4",
    type: "scooter",
    lat: 52.522,
    lng: 13.418,
    name: "bult e-scooter #881",
    provider: "bult",
    battery: 77,
    model: "B-Spark",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 1.2, perMinute: 0.25, perKm: 0.16 },
  },
  {
    id: "c-1",
    type: "car",
    lat: 52.51,
    lng: 13.38,
    name: "bult City EV",
    provider: "bult",
    battery: 46,
    model: "Volt Mini",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 2.5, perMinute: 0.39, perKm: 0.3 },
  },
  {
    id: "c-2",
    type: "car",
    lat: 52.506,
    lng: 13.392,
    name: "bult Urban Hatch",
    provider: "bult",
    fuel: 62,
    model: "Roadster S",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 2.5, perMinute: 0.41, perKm: 0.32 },
  },
  {
    id: "c-3",
    type: "car",
    lat: 52.527,
    lng: 13.394,
    name: "miluz Compact",
    provider: "miluz",
    fuel: 74,
    model: "MZ-Compact",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 2.2, perMinute: 0.36, perKm: 0.28 },
  },
  {
    id: "c-4",
    type: "car",
    lat: 52.531,
    lng: 13.408,
    name: "miluz Family Plus",
    provider: "miluz",
    fuel: 35,
    model: "MZ-Family",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 2.8, perMinute: 0.44, perKm: 0.34 },
  },
  {
    id: "b-1",
    type: "bike",
    lat: 52.524,
    lng: 13.401,
    name: "line e-bike #42",
    provider: "line",
    battery: 72,
    model: "L-Bike",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 0.8, perMinute: 0.14, perKm: 0.06 },
  },
  {
    id: "b-2",
    type: "bike",
    lat: 52.515,
    lng: 13.389,
    name: "rabbit bike #19",
    provider: "rabbit bike",
    battery: 91,
    model: "RB-E2",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 0.5, perMinute: 0.09, perKm: 0.04 },
  },
  {
    id: "b-3",
    type: "bike",
    lat: 52.528,
    lng: 13.377,
    name: "rabbit bike #77",
    provider: "rabbit bike",
    battery: 58,
    model: "RB-E2",
    status: "available",
    pricing: { currency: "EUR", unlockPrice: 0.5, perMinute: 0.09, perKm: 0.04 },
  },
  {
    id: "st-1",
    type: "station",
    lat: 52.525,
    lng: 13.369,
    name: "Berlin Hauptbahnhof",
    provider: "DB",
    status: "available",
  },
  {
    id: "st-2",
    type: "station",
    lat: 52.509,
    lng: 13.376,
    name: "Potsdamer Platz",
    provider: "BVG",
    status: "available",
  },
  {
    id: "st-3",
    type: "station",
    lat: 52.521,
    lng: 13.413,
    name: "Alexanderplatz",
    provider: "BVG",
    status: "available",
  },
];
